Fix bug in snis_launcher and update_assets_from_launcher.sh
snis_update_assets needs destdir to be a relative path.

Signed-off-by: Stephen M. Cameron <stephenmcameron@gmail.com>

diff --git a/snis_launcher b/snis_launcher
--- a/snis_launcher
+++ b/snis_launcher
@@ -634,7 +634,15 @@ check_for_asset_updates()
 
 	# copy local assets first
 	echo "Updating local assets..."
-	${SNIS_UPDATE_ASSETS} --force --destdir "$SNIS_ASSET_DIR_ROOT" --srcdir ${DESTDIR}${PREFIX}/share/snis ;
+	echo "Changing to ${DESTDIR}${PREFIX}"
+	cd ${DESTDIR}${PREFIX}
+	if [ "$?" != "0" ]
+	then
+		echo "Failed to cd to ${DESTDIR}${PREFIX}" 1>&2
+		return
+	fi
+
+	${SNIS_UPDATE_ASSETS} --force --destdir "$SNIS_ASSET_DIR_ROOT" --srcdir ./share/snis ;
 	# download assets from spacenerdsinspace.com
 	echo "Downloading remote assets from asset server..."
 	${SNIS_UPDATE_ASSETS} --force --destdir "$SNIS_ASSET_DIR_ROOT" ;
