Make snis launcher spot check for assets
This is to catch the case when the user runs "make"
but not "make assets" nor "make update-assets"

Signed-off-by: Stephen M. Cameron <stephenmcameron@gmail.com>

diff --git a/snis_launcher b/snis_launcher
--- a/snis_launcher
+++ b/snis_launcher
@@ -324,7 +324,18 @@ check_for_ip_address()
 	fi
 }
 
+spot_check_for_assets()
+{
+	if [ ! -f "${SNIS_ASSET_DIR}/models/cylinder.stl" ]
+	then
+		echo "Failed to find ${SNIS_ASSET_DIR}/models/cylinder.stl" 1>&2
+		echo "Perhaps you need to run 'make update-assets' or 'make assets'?" 1>&2
+		exit 1
+	fi
+}
+
 check_for_ip_address
+spot_check_for_assets
 
 while true
 do
